export const tableSettings = {
  persistence: {
    page: {
      size: true,
      page: true,
    },
  },
  columnDefaults: {
    tooltip: true,
  },
  headerFilterLiveFilterDelay: 100,
  index: "id",
  reactiveData: true,
  printAsHtml: true,
  printRowRange: "selected",
  persistenceID: "gateway",
  pagination: true,
  paginationMode: "remote",
  paginationSize: 5,
  paginationSizeSelector: [5, 10, 25, 50],
  filterMode: "remote",
  addRowPos: "top",
  layout: "fitDataFill",
  responsiveLayout: "collapse",
  rowHeader: {
    formatter: "responsiveCollapse",
    width: 30,
    minWidth: 30,
    hozAlign: "center",
    resizable: false,
    headerSort: false,
    tooltip: true,
  },
};

export const icons = {
  edit: "/assets/images/icon/edit.svg",
  delete: "/assets/images/icon/trash-2.svg",
  extract_caif: "/assets/images/icon/download.svg",
  extract_client_info: "/list.svg",
  extract_bos: "/assets/images/icon/download.svg",
  approve_lvl_1: "/assets/images/icon/check-circle.svg",
  approve_lvl_2: "/assets/images/icon/check-circle.svg",
  history: "/assets/images/icon/history.png",
  view: "/assets/images/icon/eye.svg",
  add_permission: "/assets/images/icon/file-plus.svg",
  add_billing: "/assets/images/icon/file-plus.svg",
  add_business_unit: "/assets/images/icon/file-plus.svg",
  add_control: "/assets/images/icon/file-plus.svg",
  add_process_rule: "/assets/images/icon/file-plus.svg",
  add_process: "/assets/images/icon/file-plus.svg",
  add_event: "/assets/images/icon/file-plus.svg",
  add_workflow: "/assets/images/icon/file-plus.svg",
  add_env: "/assets/images/icon/file-plus.svg",
  add_credentials: "/assets/images/icon/file-plus.svg",
};
